version: '3.8'
services:
  frontend:
    build:
      context: .
      # target: 'develop-stage' #develop-stage
      # target: 'build-stage' #build-stage
      target: 'production-stage' #production-stage
    ports:
    - '8081:80'
    # command: /bin/sh -c "yarn serve"