version: '3.8'
services:
  frontend:
    build:
      context: .
      # target: 'develop-stage' #develop-stage
      target: 'production-stage' #production-stage
    ports:
      - '8081:80'
    restart: always
    working_dir: /usr/share/nginx/html
    # command: /bin/sh -c "yarn serve"